"""Explicit competition identifiers shared by supported product providers."""

from __future__ import annotations

COMPETITION_CROSSWALKS: dict[str, dict[str, tuple[str, str]]] = {
    "openfootball": {
        "br.1": ("api_football", "71"),
        "ch.1": ("api_football", "207"),
        "de.1": ("api_football", "78"),
        "de.cup": ("api_football", "81"),
        "en.1": ("api_football", "39"),
        "en.2": ("api_football", "40"),
        "en.3": ("api_football", "41"),
        "en.4": ("api_football", "42"),
        "es.1": ("api_football", "140"),
        "fr.1": ("api_football", "61"),
        "fr.2": ("api_football", "62"),
        "it.1": ("api_football", "135"),
        "it.2": ("api_football", "136"),
        "mls": ("api_football", "253"),
        "mx.1": ("api_football", "262"),
        "nl.1": ("api_football", "88"),
        "pt.1": ("api_football", "94"),
        "sco.1": ("api_football", "179"),
        "tr.1": ("api_football", "203"),
        "uefa.cl": ("api_football", "2"),
    },
    "football_data_uk": {
        "B1": ("api_football", "144"),
        "D1": ("api_football", "78"),
        "D2": ("api_football", "79"),
        "E0": ("api_football", "39"),
        "E1": ("api_football", "40"),
        "E2": ("api_football", "41"),
        "E3": ("api_football", "42"),
        "EC": ("api_football", "43"),
        "F1": ("api_football", "61"),
        "F2": ("api_football", "62"),
        "G1": ("api_football", "197"),
        "I1": ("api_football", "135"),
        "I2": ("api_football", "136"),
        "N1": ("api_football", "88"),
        "P1": ("api_football", "94"),
        "SC0": ("api_football", "179"),
        "SC1": ("api_football", "180"),
        "SC2": ("api_football", "183"),
        "SC3": ("api_football", "184"),
        "SP1": ("api_football", "140"),
        "SP2": ("api_football", "141"),
        "T1": ("api_football", "203"),
    },
}
