#!/bin/sh

if [ -z "${FOOTBALL_PROJECT_ROOT:-}" ]; then
	FOOTBALL_PROJECT_ROOT=$(pwd)
fi

FOOTBALL_TOOLS_DIR="$FOOTBALL_PROJECT_ROOT/.tools"
FOOTBALL_TOOLS_BIN="$FOOTBALL_TOOLS_DIR/bin"
FOOTBALL_GO_ROOT="$FOOTBALL_TOOLS_DIR/go/1.27.0"
FOOTBALL_RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"
FOOTBALL_RUST_BIN="$FOOTBALL_RUSTUP_HOME/toolchains/1.97.1-aarch64-apple-darwin/bin"

PATH="$FOOTBALL_TOOLS_BIN:$FOOTBALL_GO_ROOT/bin:$FOOTBALL_RUST_BIN:$PATH"
UV_CACHE_DIR="$FOOTBALL_PROJECT_ROOT/.local/uv-cache"
GOCACHE="$FOOTBALL_PROJECT_ROOT/.local/go-cache"
GOMODCACHE="$FOOTBALL_PROJECT_ROOT/.local/go-mod-cache"
GOBIN="$FOOTBALL_TOOLS_BIN"
GOLANGCI_LINT_CACHE="$FOOTBALL_PROJECT_ROOT/.local/golangci-lint-cache"

export FOOTBALL_PROJECT_ROOT FOOTBALL_TOOLS_DIR FOOTBALL_TOOLS_BIN
export FOOTBALL_GO_ROOT FOOTBALL_RUSTUP_HOME FOOTBALL_RUST_BIN
export PATH UV_CACHE_DIR GOCACHE GOMODCACHE GOBIN GOLANGCI_LINT_CACHE
